### ISSUE TITLE
Better document how to get service account tokens on modern Kubernetes

### ISSUE THREAD

**Issue by chadlwilson** [gocd/gocd-kubernetes-based-secrets-plugin#167]
In newer Kubernetes versions, indefinite lifetime service account tokens appear to have gone out of fashion, and there is no automation creation of a `Secret` for a token. If you want such a thing you need to create one with something like the below (using a GoCD instance and secrets in the `gocd` namespace, and re-using its default service account):

https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: gocd-sa-secret
  namespace: gocd
  annotations:
    kubernetes.io/service-account.name: gocd
type: kubernetes.io/service-account-token
```

The plugin could do with documenting this better, including removing the misleading stuff on the configuration? Arguably should support retrieval of tokens dynamically. Yikes.
